name: hierasafe-flow
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.4
  - torchvision
  - pytorch-cuda=12.4
  - numpy
  - pillow
  - pyyaml
  - pip:
      - -r requirements.txt

